spring.application.name=BootRESTProj09-ActorAPI-MINIProject

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sbms99
spring.datasource.username=NA
spring.datasource.password=NA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/ActorAPI-Swagger

server.port=8987